name: unit_testing

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    container: argovis/wod2mat:dev

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run_tests
        run: pytest tests/*.py